version: "3.1"
services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:latest"
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: grocery_shop
      MYSQL_ROOT_PASSWORD: codegym2023
  springboot-app:
    container_name: grocery-shop-app
    image: grocery-shop
    build: .
    ports:
      - 9090:8080
    depends_on:
      - mysqldb
    env_file:
      - variables.env

