version: "3.1"
services:
  mysql:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: grocery_shop
      MYSQL_ROOT_PASSWORD: codegym2023
  react-app:
    container_name: anhnhan/grocery_shop:grocery-shop-client
    image: grocery-shop-client
    ports:
      - 3000:3000




